[project]
name = "medaillen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.2.0",
    "html5lib>=1.1",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
